### ISSUE TITLE
[Api Docs 2.0] Add Anchor Tags for <= h3

### ISSUE THREAD

**Issue by hamelsmu** [Netflix/metaflow-docs#56]
We would like to have Anchor Tags in the documentation so we can link to specific sections, this is especially helpful for API docs when there are many sections on a page.

cc: @obgibson

**Comment by obgibson** [comment]
Done

**Comment by hamelsmu** [comment]
@obgibson Okay two requests related to this: 

- I still see h3 tags without anchor tags.  
![image](https://user-images.githubusercontent.com/1483922/174875339-2fbd6cb2-7cf6-4dc2-9c5c-3192cdf2e35f.png)

The URL is http://localhost:3000/api/client

- Can we also include anchor tags for H4 as well?  

🙇🏽 Thank you, I'lll go ahead and reopen this

**Comment by obgibson** [comment]
Added # links next to the targets
